version: "3.9"
services:
  redis:
    image: redis
    container_name: 'redis'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 #--loglevel warning --requirepass ${REDIS_DEFAULT_PASS}
    volumes:
      - ./redis:/var/lib/redis/data

  memcache:
    image: memcached
    container_name: 'memcache'
    restart: always
    ports:
      - '11211:11211'
    volumes:
      - ./cache:/var/lib/cache/data
